Service:
  TonConfig: "tonlib.config.json.example"
  ContractAddress: "kf_rcyKp9D2jVwr17-QDrrKmkjlZ4aP88Xaq54hPZAXR2nx9"
  LiteClient: "bin/lite-client"
  LiteClientConfig: "ton-lite-client-test1.config.json"
  ResolveQuery: "resolve-query.fif"
  KeyFileBase: "owner"
  SavedTrxLt: "trxlt.save"