Service:
  TonConfig: "tonlib.config.json.example"
  ContractAddress: "kf8Yo2glckNPd0UMkWOdz5H6TSgVJs7Qg-_4Sl9kL6mEzeju"
  LiteClient: "bin/lite-client"
  LiteClientConfig: "ton-lite-client-test1.config.json"
  ResolveQuery: "resolve-query.fif"
  KeyFileBase: "owner"
  SavedTrxLt: "trxlt.save"
